import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Wibutime :: Home",
  description: "Generated by create next app",
};

export default function HomeLayout({
  top_user,
  top_views,
  children,
}: Readonly<{
  top_user: React.ReactNode;
  top_views: React.ReactNode;
  children: React.ReactNode;
}>) {
  return (
    <main className="px-4 min-h-dvh overflow-y-auto pb-4 pt-[88px] flex flex-col gap-4">
      {children}
      {top_views}
      {top_user}
    </main>
  );
}
