import { IBM_Plex_Serif } from 'next/font/google';

import { Toaster } from '@workspace/ui/components/toaster';
import '@workspace/ui/globals.css';
import { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
const ibmPlexSerif = IBM_Plex_Serif({
  variable: '--font-ibm-plex-serif',
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${ibmPlexSerif.variable} antialiased relative`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
