export enum MessageCode {
  // Success messages
  SUCCESS = "SUCCESS",
  CREATED = "CREATED",
  UPDATED = "UPDATED",
  DELETED = "DELETED",

  // Authentication related messages
  USERNAME_OR_EMAIL_EXISTS = "USERNAME_OR_EMAIL_EXISTS",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  UNAUTHORIZED = "UNAUTHORIZED",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  INVALID_TOKEN = "INVALID_TOKEN",
  USERNAME_OR_PASSWORD_INVALID = "USERNAME_OR_PASSWORD_INVALID",
  INACTIVE_ACCOUNT = "INACTIVE_ACCOUNT",
  ACCOUNT_LOCKED = "ACCOUNT_LOCKED",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  CHANGE_PASSWORD = "CHANGE_PASSWORD",

  // Validation messages
  INVALID_INPUT = "INVALID_INPUT",
  REQUIRED_FIELD = "REQUIRED_FIELD",
  INVALID_FORMAT = "INVALID_FORMAT",

  // Resource status messages
  NOT_FOUND = "NOT_FOUND",
  ALREADY_EXISTS = "ALREADY_EXISTS",
  FORBIDDEN = "FORBIDDEN",

  // Server related messages
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  BAD_REQUEST = "BAD_REQUEST",
  QUERY_ERROR = "QUERY_ERROR",
}
